import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { locale, i18n } from '@/i18n.config';
import Header from '@/components/Header';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Web app',
	description: 'Generated by create next app',
};

export function generateStaticParams() {
	return i18n.locales.map(locale => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: locale };
}) {
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<Providers>
					<Header lang={params.lang} />

					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
